import { db } from '@/db';
import { cars } from '@/db/schema';

async function main() {
    const sampleCars = [
        {
            brand: 'Toyota',
            model: 'Camry',
            year: 2023,
            pricePerDay: 45,
            imageUrl: null,
            isAvailable: true,
            licensePlate: 'TYT-1234',
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            brand: 'Honda',
            model: 'Accord',
            year: 2023,
            pricePerDay: 42,
            imageUrl: null,
            isAvailable: true,
            licensePlate: 'HND-5678',
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            brand: 'BMW',
            model: '3 Series',
            year: 2024,
            pricePerDay: 95,
            imageUrl: null,
            isAvailable: false,
            licensePlate: 'BMW-9012',
            createdAt: new Date('2024-02-01').toISOString(),
        },
        {
            brand: 'Mercedes',
            model: 'C-Class',
            year: 2024,
            pricePerDay: 110,
            imageUrl: null,
            isAvailable: true,
            licensePlate: 'MBZ-3456',
            createdAt: new Date('2024-02-10').toISOString(),
        },
        {
            brand: 'Audi',
            model: 'A4',
            year: 2023,
            pricePerDay: 88,
            imageUrl: null,
            isAvailable: false,
            licensePlate: 'AUD-7890',
            createdAt: new Date('2024-02-15').toISOString(),
        },
        {
            brand: 'Ford',
            model: 'Mustang',
            year: 2023,
            pricePerDay: 75,
            imageUrl: null,
            isAvailable: true,
            licensePlate: 'FRD-2345',
            createdAt: new Date('2024-03-01').toISOString(),
        },
        {
            brand: 'Chevrolet',
            model: 'Malibu',
            year: 2022,
            pricePerDay: 38,
            imageUrl: null,
            isAvailable: true,
            licensePlate: 'CHV-6789',
            createdAt: new Date('2024-03-10').toISOString(),
        },
        {
            brand: 'Tesla',
            model: 'Model 3',
            year: 2024,
            pricePerDay: 120,
            imageUrl: null,
            isAvailable: false,
            licensePlate: 'TSL-0123',
            createdAt: new Date('2024-03-15').toISOString(),
        },
        {
            brand: 'Nissan',
            model: 'Altima',
            year: 2023,
            pricePerDay: 40,
            imageUrl: null,
            isAvailable: true,
            licensePlate: 'NSN-4567',
            createdAt: new Date('2024-04-01').toISOString(),
        },
        {
            brand: 'Hyundai',
            model: 'Sonata',
            year: 2023,
            pricePerDay: 35,
            imageUrl: null,
            isAvailable: true,
            licensePlate: 'HYN-8901',
            createdAt: new Date('2024-04-10').toISOString(),
        },
        {
            brand: 'Mazda',
            model: '6',
            year: 2023,
            pricePerDay: 43,
            imageUrl: null,
            isAvailable: true,
            licensePlate: 'MZD-2345',
            createdAt: new Date('2024-04-20').toISOString(),
        },
        {
            brand: 'Volkswagen',
            model: 'Passat',
            year: 2023,
            pricePerDay: 48,
            imageUrl: null,
            isAvailable: true,
            licensePlate: 'VWG-6789',
            createdAt: new Date('2024-05-01').toISOString(),
        },
        {
            brand: 'Kia',
            model: 'K5',
            year: 2024,
            pricePerDay: 41,
            imageUrl: null,
            isAvailable: false,
            licensePlate: 'KIA-0123',
            createdAt: new Date('2024-05-10').toISOString(),
        },
        {
            brand: 'Subaru',
            model: 'Legacy',
            year: 2023,
            pricePerDay: 46,
            imageUrl: null,
            isAvailable: true,
            licensePlate: 'SBR-4567',
            createdAt: new Date('2024-05-20').toISOString(),
        },
        {
            brand: 'Lexus',
            model: 'ES',
            year: 2024,
            pricePerDay: 105,
            imageUrl: null,
            isAvailable: true,
            licensePlate: 'LXS-8901',
            createdAt: new Date('2024-06-01').toISOString(),
        },
        {
            brand: 'Acura',
            model: 'TLX',
            year: 2023,
            pricePerDay: 68,
            imageUrl: null,
            isAvailable: true,
            licensePlate: 'ACR-2345',
            createdAt: new Date('2024-06-10').toISOString(),
        },
        {
            brand: 'Infiniti',
            model: 'Q50',
            year: 2023,
            pricePerDay: 72,
            imageUrl: null,
            isAvailable: false,
            licensePlate: 'INF-6789',
            createdAt: new Date('2024-06-20').toISOString(),
        },
        {
            brand: 'Genesis',
            model: 'G70',
            year: 2024,
            pricePerDay: 80,
            imageUrl: null,
            isAvailable: true,
            licensePlate: 'GNS-0123',
            createdAt: new Date('2024-07-01').toISOString(),
        },
    ];

    await db.insert(cars).values(sampleCars);
    
    console.log('✅ Cars seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});